### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by rajcheval** [avantoss/vault-infra#10]
I have setup a vault cluster based on the instructions.
I created a self signed certificate
I did copy SSL certs to resource bucket.
I terminated the instances and new instance were created.
User data script did download the ssl certs from S3 bucket
when I run vault operatory init I get the following error.
 
Error initializing: Put https://127.0.0.1:8200/v1/sys/init: x509: certificate signed by unknown authority
Instructions did not say anything about CA cert.
so I created a new cert.crt file where I combined the domain cert and ca cert in 1 file.
The file contained domain cert first followed by ca cert.
Even after creating this new cert file I am getting this error:
Error initializing: Put https://127.0.0.1:8200/v1/sys/init: x509: certificate signed by unknown authority

I am wondering if you have run into this before.
How did you generate your self sign certificates?

I used this module to create ssl cert
https://github.com/hashicorp/terraform-aws-vault/tree/master/modules/private-tls-cert

It create public key, private key and CA key for me.

**Comment by lingrino** [comment]
Hello @rajcheval!

If you are using a self signed certificate and you want to access vault locally from the instance then you need to make sure that the system trusts your self signed certificate.

The exact way of doing this depends on the OS. On `centos` you need to copy the CA file into `/etc/pki/ca-trust/source/anchors/` and then run `update-ca-trust` on the system.

I hope that helps, the specifics of SSL trust are somewhat beyond the purposes of this module.

**Comment by rajcheval** [comment]
@lingrino Yes I was able to find the instruction to update the ca in aws linux 2 this past weekend. I followed the exact same steps you suggested and they worked for me. Thanks
