### ISSUE TITLE
SSL certificates

### ISSUE THREAD

**Issue by irbekrm** [avantoss/vault-infra#13]
Thanks for open sourcing this great project!
I have a question about step 9 in the 'Getting Started' section. It asks  to upload SSL cert and private key to an S3 bucket. Was I supposed to generate the cert and the key manually beforehand or does this refer to some resources generated by Terraform?

**Comment by lingrino** [comment]
Hi @irbekrm! These are certs that you should already have or should generate on your own and should be valid for the vault hostname that you've chosen. Note that with this setup you have certs on the AWS load balancer _and_ on the vault hosts themselves. Step 9 refers to certs on the host and `var. alb_certificate_arn` refers to the cert on the load balancer. If you don't need the extra security from certs on the hosts you can disable that in the vault config file.

**Comment by irbekrm** [comment]
Hi @lingrino, thanks a lot! I didn't realize there were separate certs needed for vault hosts and alb.
