### ISSUE TITLE
using aws linux 2

### ISSUE THREAD

**Issue by rajpolaris** [avantoss/vault-infra#9]
The packer sample json refers to CentOS Linux 7 x86_64 HVM EBS *.
I was wondering if you see any problems with using AWS Linux 2 to build the AMI.
I am not sure if there anything in the provisioning process that will break if we use AWS Linux 2.

**Comment by lingrino** [comment]
Hi @rajpolaris. I think this is a great idea. I've been running vault on Amazon Linux 2 for a while with no issues and I don't think there would be any changes. Let me know if you want to try a PR on your own or I can work on it in a couple weeks probably.

**Comment by rajpolaris** [comment]
@lingrino I will test building an AWS Linux2 ami and if it all works I can submit a PR. Thanks

**Comment by rajcheval** [comment]
Ansible playbook will need to change for Linux2.
Here is the error I am getting.

    vault: fatal: [default]: FAILED! => {
    vault:     "changed": false,
    vault:     "failed": true,
    vault:     "invocation": {
    vault:         "module_args": {
    vault:             "allow_downgrade": false,
    vault:             "conf_file": null,
    vault:             "disable_gpg_check": false,
    vault:             "disablerepo": null,
    vault:             "enablerepo": null,
    vault:             "exclude": null,
    vault:             "install_repoquery": true,
    vault:             "installroot": "/",
    vault:             "list": null,
    vault:             "name": [
    vault:                 "epel-release"
    vault:             ],
    vault:             "security": false,
    vault:             "skip_broken": false,
    vault:             "state": "latest",
    vault:             "update_cache": false,
    vault:             "validate_certs": true
    vault:         }
    vault:     },
    vault:     "msg": "No package matching 'epel-release' found available, installed or updated",
    vault:     "rc": 126,
    vault:     "results": [
    vault:         "No package matching 'epel-release' found available, installed or updated"
    vault:     ]


I don't have ansible experience.  Seems to me like epel-release is not present on AWS Linux 2. Let mne know if you have any suggestions.

**Comment by lingrino** [comment]
With Amazon Linux 2 you shouldn't need the `epel-release` package, try removing it.

**Comment by rajcheval** [comment]
I end up installing epel-release in aws linux 2 using a command statement in ansible. Another issue I ran into was Ansible 2.8 yum file locked issue. I downgraded to 2.7 and it all worked. 
I have vault cluster up and running. It is working well. Thanks for your help
